FROM php:8.0-apache

# Install the pdo extension
RUN apt-get update && apt-get install -y libpq-dev \
    && docker-php-ext-install pdo

# Install the pdo_mysql extension
RUN docker-php-ext-install pdo_mysql
